### ISSUE TITLE
Events Preview screen crashes

### ISSUE THREAD

**Issue by lemonboston** [schedjoules/android-public-calendars-sdk#13]
Apparently, the `net.opacapp.multilinecollapsingtoolbar.CollapsingToolbarLayout` library removed in #8 is actually used in a layout and now it causes runtime crash. (Not sure why build succeeds without it)
So it has to be put back and need to solve the related proguard issue.

**Comment by dmfs** [comment]
I suggest you switch directly to our fork which we're also using in the event-discovery SDK. It should be 100% compatible to the "original" one, but based on a newer upstream version than the one you removed.

**Comment by lemonboston** [comment]
Yep, done it already eventually, this comment would have saved a something close to an hour.. (builds are very slow with proguard).
